### ISSUE TITLE
Declared Function Isn't Recognized During the Parsing Process

### ISSUE THREAD

**Issue by Maxwell-Alexius** [Maxwell-Alexius/Wyrd-Lang#26]
**What?**
Although we can declare function using `def <funcName>(args...)`, the function isn't parsed whenever we want to call the function.

**How?**
Wyrd Program:
```
def funcA(x: Num, y: Num): Num => x + y
funcA 1, 2
```

Couldn't recognize the `comma` token, and:

```
def funcA(x: Num, y: Num): Num => x + y
funcA(1, 2)
```

Couldn't recognize the `rparen` token, the reason why it can recognize the left parenthesis is because it is being parsed as prioritized expression.

**Expected behavior?**
Should parsed as function invocation expression normally.

**Screenshots**
None

**Additional context**
Code sample:

```
age = 1 + 2 * 3 + 4

stage = if age <= 18 => "Teenager"
        elif age < 60 then
          "Adult"
        elif age < 100 => "Elder"
        else then
          "Centenarian"
        end

def funcA(x: Num, y: Num): Num => x + y
def funcB(x: Num, y: Num, z: Num): Num do
  foo = x + y
  bar = foo * z - x
  bar
end

funcA(1, 2)
```

Error Message:
```
 FAIL  src/test/compiler.spec.ts
  Compiler
    ✕ compiles the sample program successfully (2143ms)

  ● Compiler › compiles the sample program successfully

    Parser: Unhandled token type of `rparen`

      1 | export function ParserError(msg: string): never {
    > 2 |   throw new Error(`Parser: ${msg}`);
        |         ^
      3 | }
      4 |
      5 | export function ParserErrorIf(bool: boolean, msg: string): void {

      at Object.ParserError (src/parser/error.ts:2:9)
      at parseExpr (src/parser/index.ts:110:5)
      at Object.parse (src/parser/index.ts:120:20)
      at Object.compile (src/index.ts:13:15)
      at Object.<anonymous> (src/test/compiler.spec.ts:6:12)
      at fulfilled (src/test/compiler.spec.ts:4:58)

Test Suites: 1 failed, 7 passed, 8 total
Tests:       1 failed, 91 passed, 92 total
Snapshots:   0 total
Time:        4.465s
Ran all test suites.

Watch Usage: Press w to show more.
```

**Comment by Maxwell-Alexius** [comment]
Solved from PR #28
